development:
  adapter: postgresql
  encoding: unicode
  database: electricstoragev2_dev
  pool: 5
  username: postgres
  password:	postgres

test:
  adapter: postgresql
  encoding: unicode
  database: electricstoragev2_test
  pool: 5
  username: postgres
  password:	postgres
